version: '3'

services:
  # MIDDLEWARE SERVICE

  sofialys-middleware :
    image: sofialys-middleware:latest
    build:
      context: ../sofialys-middleware
    container_name: sofialys-middleware
    ports:
      - "8000:80"
    volumes:
      - ../sofialys-middleware:/var/www/html

  # MAUTIC CORE SERVICE

  sofialys-mautic:
    image: sofialys-core:latest
    build:
      context: ../core
      dockerfile: Dockerfile
      args:
        -ssh_prv_key: ''
        -ssh_pub_key: ''
    container_name: sofialys-mautic
    ports:
      - "9000:80"
    links:
      - sofialys-db:mysql
    depends_on:
      - sofialys-db
    volumes:
      - mautic_data:/var/www/html
    environment:
      - MAUTIC_DB_HOST=sofialys-db
      - MYSQL_PORT_3306_TCP=3306
      - MAUTIC_DB_USER=root
      - MAUTIC_DB_PASSWORD=mysecret
      - MAUTIC_DB_NAME=mautic
      - MAUTIC_RUN_CRON_JOBS=true
      - ssh_prv_key=${ssh_prv_key}
      - ssh_pub_key=${ssh_pub_key}
    networks:
      - mautic_net

  # DB SERVER

  sofialys-db:
    image: percona/percona-server:5.7
    container_name: sofialys-db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysecret
    command:
      --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    networks:
      - mautic_net
volumes:
  mysql_data:
    driver: local
  mautic_data:
    driver: local
networks:
  mautic_net:
    driver: bridge